Repository UniStuttgart-VISUS/damast, pull requests merged in 2023-05, with the labels that each got.

#189 Feature/golden layout v2.6.0
  CHANGELOG
  package-lock.json
  package.json
  src/scss/vis/_goldenlayout-theme.scss
  src/scss/vis/_modals.scss
  src/vis/confidence-pane.ts
  src/vis/default-layout.ts
  src/vis/entry.ts
  src/vis/goldenlayout-util.ts
  src/vis/history-tree.ts
  src/vis/location-list.ts
  src/vis/map.ts
  src/vis/religion-hierarchy.ts
  src/vis/settings-pane.ts
  src/vis/source-pane.ts
  src/vis/tags.ts
  src/vis/timeline.ts
  src/vis/untimed-display.ts
  src/vis/view.ts
  webpack.config.js
Labels: enhancement

#191 Add PacificNotes publication
  README.md
  damast/root/templates/root/index.html
  docs/bibliography.bib
  docs/documentation.tex
  documentation.pdf
Labels: documentation

#195 fix issue 194
  CHANGELOG
  damast/postgres_rest_api/place.py
Labels: bug

#199 Feature/better logos
  CHANGELOG
  damast/root/templates/root/index.html
Labels: bug
